### PR TITLE
Allow config override per vhost

### PR DESCRIPTION
**Pull request by lammensj**

### CODE REVIEW

**Comment by lmakarov** [comment]
@lammensj what would be the case when overriding http vs https vhost settings separately would be useful/required?

**Comment by lammensj** [comment]
One of the most common cases is redirecting from http to https. I know this can the first rule of many vhost configuration lines, but it would be nice if I could just separate them.
Another use case that springs to mind are forward proxies over SSL.

**Review by lmakarov — APPROVED** [review]

**Comment by lmakarov** [comment]
I have to admin that it took way too long to get back to this PR. Sorry about that. @lammensj if you are still interested in contributing this enhancement, please submit a new PR based on the most recent code in develop. I will have it merged right away this time 🤞😃

**Comment by lammensj** [comment]
@lmakarov no problem, I understand that managing an opensource project is not that easy and that it might take up a lot of your time 🙂 
I compared my pr with the current version, and it appears that support for http(s) is already incorporated, so I'm not going to open a new pr.
Thank you for this amazing project!

**Pull request closed without merging**
